version: '2'
services:
  nginx:
    image: nginx:1.15.3
    container_name: nginx
    links:
      - server
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  client:
    build: ./client
    container_name: client
    volumes:
      - ./client:/app
    working_dir: /app
    ports:
      - "8080:8080"
  
  server:
    build: ./server
    container_name: server
    environment:
      - NODE_ENV=production
      - APPLICATION_PORT=8081
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - "8081:8081"